version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=obs_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - "3308:3306"
    volumes:
      - /data/mysql


  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/obs_database?allowPublicKeyRetrieval=true&useSSL=false

